name: Create AWS S3 Bucket

on:
  push:
    paths:
      - 'resource.json'
  workflow_dispatch:

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Parse JSON file
      id: parse_json
      run: |
        bucket_name=$(jq -r '.BucketName' resource.json)
        echo "::set-output name=bucket_name::$bucket_name"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create S3 bucket
      run: |
        aws s3api create-bucket --bucket ${{ steps.parse_json.outputs.bucket_name }} --region us-east-1
