name: Create Resources

on:
  push:
    paths:
      - 'resource.json'
  workflow_dispatch:

jobs:
  create-resources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Parse JSON file
      id: parse_json
      run: |
        platform_type=$(jq -r '.PlatformType' resource.json)
        echo "platform_type=$platform_type" >> $GITHUB_ENV
        resources=$(jq '.Resources | length' resource.json)
        echo "num_resources=$resources" >> $GITHUB_ENV

        for ((i=0; i<$resources; i++)); do
          resource=$(jq -c .Resources[$i] resource.json)
          resource_type=$(echo $resource | jq -r '.ResourceType')
          resource_name=$(echo $resource | jq -r '.ResourceName')
          echo "resource_${i}_type=$resource_type" >> $GITHUB_ENV
          echo "resource_${i}_name=$resource_name" >> $GITHUB_ENV
          echo "resource_${i}_config=$(echo $resource)" >> $GITHUB_ENV
        done

    - name: Configure Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Create AWS Resources
      if: ${{ env.platform_type == 'AWS' }}
      run: |
        num_resources=${{ env.num_resources }}
        for ((i=0; i<$num_resources; i++)); do
          resource_type=${{ env[format('resource_%s_type', i)] }}
          resource_name=${{ env[format('resource_%s_name', i)] }}
          resource_config=${{ env[format('resource_%s_config', i)] }}
          
          echo "Creating $resource_type named $resource_name"
          
          case $resource_type in
            S3)
              echo "resource \"aws_s3_bucket\" \"$resource_name\" {
                bucket = \"$resource_name\"
              }" > main.tf
              ;;
            EC2)
              ami=$(echo $resource_config | jq -r '.Ami')
              instance_type=$(echo $resource_config | jq -r '.InstanceType')
              echo "resource \"aws_instance\" \"$resource_name\" {
                ami           = \"$ami\"
                instance_type = \"$instance_type\"
              }" > main.tf
              ;;
            SNS)
              echo "resource \"aws_sns_topic\" \"$resource_name\" {
                name = \"$resource_name\"
              }" > main.tf
              ;;
            *)
              echo "Unsupported resource type: $resource_type"
              exit 1
              ;;
          esac

          terraform init
          terraform apply -auto-approve
        done

    - name: Process Databricks and Snowflake
      if: ${{ env.platform_type == 'DATABRICK' || env.platform_type == 'DATAFLAKE' }}
      run: |
        if [[ "${{ env.platform_type }}" == "DATABRICK" ]]; then
          echo "Processing Databricks resources..."
          # Add your Databricks related commands here
        elif [[ "${{ env.platform_type }}" == "DATAFLAKE" ]]; then
          echo "Processing Snowflake resources..."
          # Add your Snowflake related commands here
        fi
